version: '3'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: review-sense
      POSTGRES_USER: review-sense
      POSTGRES_PASSWORD: review-sense
      POSTGRES_NAME: review-sense
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
